version: '2'

services:
  watchdog:
    container_name: watchdog
    image: buanet/watchdog:latest
    hostname: watchdog
    restart: always
    environment:
      - WATCHDOG_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
